### ISSUE TITLE
iCal feed url incorrect, missing a /

### ISSUE THREAD

**Issue by andymckay** [mozilla/airmozilla#335]
/tmp curl -q https://air.mozilla.org/calendar/public.ics | grep URL    
URL:https://air.mozilla.orgwebdev-extravaganza-june-2015/
URL:https://air.mozilla.orgmozilla-weekly-project-meeting-HLS/
URL:https://air.mozilla.orgmozilla-weekly-project-meeting-20150601/
URL:https://air.mozilla.orgworld-wide-haxe-conference-2015/
URL:https://air.mozilla.orgparticipation-at-mozilla-20150528/
URL:https://air.mozilla.orgreps-weekly-20150528/

**Comment by andymckay** [comment]
This seems to work in the tests locally, so not sure what the problem is, but it looks like the reverse is wierdly missing a leading slash.

**Comment by peterbe** [comment]
Thanks. I really need to do a release soon https://bugzilla.mozilla.org/show_bug.cgi?id=1168445
